export interface CountryOption {
  name: string;
  code: string;
  defaultCurrency: string;
  currencySymbol: string;
  exams: string[];
  degrees: string[];
  states?: string[];
}

export const COUNTRIES: CountryOption[] = [
  {
    name: "India",
    code: "IN",
    defaultCurrency: "INR",
    currencySymbol: "₹",
    degrees: ["B.Tech / B.E.", "B.Arch", "M.Tech / M.E.", "MBA", "MBBS", "B.Sc / BCA"],
    exams: [
      // Telangana & Andhra Pradesh
      "TG EAPCET (Telangana EAPCET)",
      "AP EAPCET (Andhra Pradesh EAPCET)",
      "TS ECET (Telangana Lateral Entry)",
      "AP ECET (Andhra Pradesh Lateral Entry)",
      "TS POLYCET",
      "AP POLYCET",
      // National
      "JEE Main",
      "JEE Advanced",
      "NEET UG",
      "BITSAT",
      "VITEEE",
      "SRMJEEE",
      "MET (Manipal)",
      "COMEDK UGET (Karnataka Private)",
      "KCET (Karnataka State)",
      "MHT-CET (Maharashtra)",
      "WBJEE (West Bengal)",
      "KEAM (Kerala)",
      "TNEA (Tamil Nadu)",
      "GUJCET (Gujarat)",
      "CUET UG",
      "GATE",
      "CAT",
      "OTHER",
    ],
    states: [
      "Telangana",
      "Andhra Pradesh",
      "Karnataka",
      "Maharashtra",
      "Tamil Nadu",
      "Kerala",
      "Delhi NCR",
      "Gujarat",
      "Uttar Pradesh",
      "West Bengal",
      "Rajasthan",
      "Madhya Pradesh",
      "Punjab",
      "Haryana",
      "Odisha",
      "Bihar",
      "Assam",
      "Goa",
      "Other States / UTs",
    ],
  },
  {
    name: "United States",
    code: "US",
    defaultCurrency: "USD",
    currencySymbol: "$",
    degrees: ["Bachelor of Science (BS)", "Bachelor of Arts (BA)", "Master of Science (MS)", "PhD"],
    exams: ["SAT", "ACT", "GRE", "TOEFL", "IELTS", "Duolingo English Test", "AP Exams"],
    states: [
      "California",
      "New York",
      "Texas",
      "Massachusetts",
      "Washington",
      "Illinois",
      "Pennsylvania",
      "Georgia",
      "Michigan",
      "Other US States",
    ],
  },
  {
    name: "United Kingdom",
    code: "UK",
    defaultCurrency: "GBP",
    currencySymbol: "£",
    degrees: ["BEng / BSc", "MEng / MSc", "MBA", "PhD"],
    exams: ["IELTS", "TOEFL", "PTE Academic", "UCAS Tariff / A-Levels", "GRE"],
    states: ["England", "Scotland", "Wales", "Northern Ireland"],
  },
  {
    name: "Canada",
    code: "CA",
    defaultCurrency: "CAD",
    currencySymbol: "CA$",
    degrees: ["Bachelor of Applied Science / BSc", "Master of Engineering / MSc", "Postgraduate Diploma"],
    exams: ["IELTS", "TOEFL", "PTE", "Duolingo English Test", "GRE"],
    states: ["Ontario", "British Columbia", "Quebec", "Alberta", "Manitoba", "Other Provinces"],
  },
  {
    name: "Germany",
    code: "DE",
    defaultCurrency: "EUR",
    currencySymbol: "€",
    degrees: ["Bachelor of Science", "Master of Science (English/German taught)"],
    exams: ["TestDaF / Goethe (German)", "IELTS", "TOEFL", "GRE", "APS Certificate"],
    states: ["Bavaria", "Baden-Württemberg", "North Rhine-Westphalia", "Berlin", "Hesse", "Other States"],
  },
  {
    name: "Australia",
    code: "AU",
    defaultCurrency: "AUD",
    currencySymbol: "A$",
    degrees: ["Bachelor of Engineering (Honours)", "Master of Information Tech / Data Science", "Master of Engineering"],
    exams: ["IELTS", "PTE Academic", "TOEFL"],
    states: ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia"],
  },
  {
    name: "Singapore",
    code: "SG",
    defaultCurrency: "SGD",
    currencySymbol: "S$",
    degrees: ["B.Eng", "B.Sc", "M.Sc", "MBA"],
    exams: ["JEE Advanced / 90%+ State Board", "SAT", "ACT", "IELTS", "TOEFL"],
    states: ["Singapore"],
  },
  {
    name: "Ireland",
    code: "IE",
    defaultCurrency: "EUR",
    currencySymbol: "€",
    degrees: ["BSc (Honours)", "MSc", "Postgraduate Diploma"],
    exams: ["IELTS", "TOEFL", "PTE", "Duolingo English Test"],
    states: ["Dublin", "Cork", "Galway", "Limerick"],
  },
];

export const ALL_CATEGORIES = [
  { value: "OC", label: "OC / General (Open Competition)" },
  { value: "BC-A", label: "BC-A (Backward Class Group A)" },
  { value: "BC-B", label: "BC-B (Backward Class Group B)" },
  { value: "BC-C", label: "BC-C (Backward Class Group C)" },
  { value: "BC-D", label: "BC-D (Backward Class Group D)" },
  { value: "BC-E", label: "BC-E (Backward Class Group E)" },
  { value: "SC", label: "SC (Scheduled Caste)" },
  { value: "ST", label: "ST (Scheduled Tribe)" },
  { value: "EWS", label: "EWS (Economically Weaker Section)" },
  { value: "OBC", label: "OBC (Other Backward Classes - Central)" },
  { value: "International", label: "International / NRI / Foreign National" },
];
