export interface InternationalCollege {
  id: string;
  name: string;
  country: string;
  city: string;
  qs_world_ranking: number;
  flag: string;
  acceptance_rate: string;
  degree_levels: string[];
  annual_tuition_usd: number;
  annual_tuition_inr_lakhs: number;
  application_fee_usd: number;
  deadlines: {
    fall: string;
    spring?: string;
  };
  required_tests: {
    undergraduate?: string;
    postgraduate?: string;
    english_proficiency: string;
  };
  stem_opt_work_permit: string;
  popular_majors: string[];
  scholarships_available: string;
  website: string;
}

export const INTERNATIONAL_COLLEGES: InternationalCollege[] = [
  // USA
  {
    id: "mit-usa",
    name: "Massachusetts Institute of Technology (MIT)",
    country: "United States",
    city: "Cambridge, Massachusetts",
    qs_world_ranking: 1,
    flag: "🇺🇸",
    acceptance_rate: "4.0%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 59750,
    annual_tuition_inr_lakhs: 50.8,
    application_fee_usd: 75,
    deadlines: { fall: "Jan 5 (Regular) / Nov 1 (Early Action)" },
    required_tests: {
      undergraduate: "SAT: 1520-1580 or ACT: 35-36",
      postgraduate: "GRE General + Subject (optional)",
      english_proficiency: "IELTS 7.5+ / TOEFL 100+",
    },
    stem_opt_work_permit: "3 Years Post-Study STEM OPT in the US",
    popular_majors: ["Computer Science", "Artificial Intelligence", "Electrical Engineering", "Quantum Computing", "Mechanical Eng."],
    scholarships_available: "100% Need-Blind Financial Aid for all admitted international undergraduates",
    website: "https://www.mit.edu",
  },
  {
    id: "stanford-usa",
    name: "Stanford University",
    country: "United States",
    city: "Stanford, California (Silicon Valley)",
    qs_world_ranking: 3,
    flag: "🇺🇸",
    acceptance_rate: "3.7%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 62484,
    annual_tuition_inr_lakhs: 53.1,
    application_fee_usd: 90,
    deadlines: { fall: "Jan 5 (Regular) / Nov 1 (Restrictive Early Action)" },
    required_tests: {
      undergraduate: "SAT: 1500-1570 or ACT: 34-36",
      postgraduate: "GRE (branch-specific)",
      english_proficiency: "TOEFL 100+ (IELTS not preferred)",
    },
    stem_opt_work_permit: "3 Years STEM OPT (Silicon Valley tech hub)",
    popular_majors: ["Computer Science", "Data Science", "Management Science & Eng", "Bioengineering"],
    scholarships_available: "Knight-Hennessy Scholars (Full funding) + Need-based institutional grants",
    website: "https://www.stanford.edu",
  },
  {
    id: "cmu-usa",
    name: "Carnegie Mellon University (CMU)",
    country: "United States",
    city: "Pittsburgh, Pennsylvania",
    qs_world_ranking: 52,
    flag: "🇺🇸",
    acceptance_rate: "11.0%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 63829,
    annual_tuition_inr_lakhs: 54.2,
    application_fee_usd: 75,
    deadlines: { fall: "Jan 3 (Regular) / Nov 1 (Early Decision)" },
    required_tests: {
      undergraduate: "SAT: 1500-1560 or ACT: 34-35",
      postgraduate: "GRE 325+ (Verbal 155+, Quant 168+)",
      english_proficiency: "IELTS 7.5+ / TOEFL 102+ / Duolingo 125+",
    },
    stem_opt_work_permit: "3 Years STEM OPT (#1 CS globally)",
    popular_majors: ["School of Computer Science", "Software Engineering", "Robotics", "Human-Computer Interaction"],
    scholarships_available: "Merit scholarships for graduate programs; assistantships (TA/RA)",
    website: "https://www.cmu.edu",
  },
  {
    id: "uc-berkeley-usa",
    name: "University of California, Berkeley (UC Berkeley)",
    country: "United States",
    city: "Berkeley, California",
    qs_world_ranking: 10,
    flag: "🇺🇸",
    acceptance_rate: "11.6%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 48500,
    annual_tuition_inr_lakhs: 41.2,
    application_fee_usd: 80,
    deadlines: { fall: "Nov 30 (UC Application deadline)" },
    required_tests: {
      undergraduate: "Test-free for UC admissions (Holistic Review)",
      postgraduate: "GRE required for specific engineering tracks",
      english_proficiency: "IELTS 7.0+ / TOEFL 90+",
    },
    stem_opt_work_permit: "3 Years STEM OPT (Direct Bay Area hiring)",
    popular_majors: ["EECS (Electrical Eng & CS)", "Data Science", "Civil Eng", "Business Administration (Haas)"],
    scholarships_available: "Berkeley International Fellowship & Graduate Student Researcher stipends",
    website: "https://www.berkeley.edu",
  },
  {
    id: "georgia-tech-usa",
    name: "Georgia Institute of Technology (Georgia Tech)",
    country: "United States",
    city: "Atlanta, Georgia",
    qs_world_ranking: 97,
    flag: "🇺🇸",
    acceptance_rate: "16.0%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 33796,
    annual_tuition_inr_lakhs: 28.7,
    application_fee_usd: 85,
    deadlines: { fall: "Jan 4 (Regular) / Oct 15 (Early Action)" },
    required_tests: {
      undergraduate: "SAT: 1400-1530 or ACT: 31-35",
      postgraduate: "GRE 318+ (Quant 165+)",
      english_proficiency: "IELTS 7.0+ / TOEFL 95+",
    },
    stem_opt_work_permit: "3 Years STEM OPT (Top ROI engineering school in the US)",
    popular_majors: ["Aerospace Engineering", "Computer Science", "Industrial Engineering", "Cybersecurity"],
    scholarships_available: "Graduate Teaching/Research Assistantships with out-of-state fee waivers",
    website: "https://www.gatech.edu",
  },

  // United Kingdom
  {
    id: "oxford-uk",
    name: "University of Oxford",
    country: "United Kingdom",
    city: "Oxford, England",
    qs_world_ranking: 3,
    flag: "🇬🇧",
    acceptance_rate: "14.5%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 44000,
    annual_tuition_inr_lakhs: 37.4,
    application_fee_usd: 95,
    deadlines: { fall: "Oct 15 (UCAS deadline for all courses)" },
    required_tests: {
      undergraduate: "MAT / PAT / TSA admissions tests",
      postgraduate: "First Class honours degree (80%+ from premier Indian univ)",
      english_proficiency: "IELTS 7.5 (min 7.0 each) / TOEFL 110+",
    },
    stem_opt_work_permit: "2 Years UK Graduate Route Work Visa",
    popular_majors: ["Computer Science", "Engineering Science", "Mathematics", "Economics & Management"],
    scholarships_available: "Clarendon Fund, Rhodes Scholarships, Reach Oxford Scholarships",
    website: "https://www.ox.ac.uk",
  },
  {
    id: "cambridge-uk",
    name: "University of Cambridge",
    country: "United Kingdom",
    city: "Cambridge, England",
    qs_world_ranking: 2,
    flag: "🇬🇧",
    acceptance_rate: "15.7%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 47000,
    annual_tuition_inr_lakhs: 39.9,
    application_fee_usd: 95,
    deadlines: { fall: "Oct 15 (UCAS deadline)" },
    required_tests: {
      undergraduate: "TMUA / ENGAA admissions tests + Cambridge College Interview",
      postgraduate: "Strong bachelor degree (CGPA 8.5+)",
      english_proficiency: "IELTS 7.5+ / TOEFL 110+",
    },
    stem_opt_work_permit: "2 Years UK Graduate Route Visa",
    popular_majors: ["Engineering Tripos", "Computer Science Tripos", "Natural Sciences", "Biotechnology"],
    scholarships_available: "Gates Cambridge Trust (Full funding), Cambridge Trust awards",
    website: "https://www.cam.ac.uk",
  },
  {
    id: "imperial-uk",
    name: "Imperial College London",
    country: "United Kingdom",
    city: "London, England",
    qs_world_ranking: 6,
    flag: "🇬🇧",
    acceptance_rate: "12.0%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 45000,
    annual_tuition_inr_lakhs: 38.2,
    application_fee_usd: 90,
    deadlines: { fall: "Jan 29 (UCAS)" },
    required_tests: {
      undergraduate: "Class 12 CBSE/ICSE: 95%+ in Maths and Physics",
      postgraduate: "GRE recommended for MS Computing; CGPA 8.0+",
      english_proficiency: "IELTS 7.0+ (min 6.5 each) / Duolingo 125+",
    },
    stem_opt_work_permit: "2 Years UK Graduate Route Visa (Central London tech hub)",
    popular_majors: ["Computing & AI", "Aeronautical Engineering", "Data Science", "Mechanical Engineering"],
    scholarships_available: "President's Undergraduate Scholarships, Commonwealth Scholarships",
    website: "https://www.imperial.ac.uk",
  },

  // Canada
  {
    id: "utoronto-canada",
    name: "University of Toronto (U of T)",
    country: "Canada",
    city: "Toronto, Ontario",
    qs_world_ranking: 21,
    flag: "🇨🇦",
    acceptance_rate: "43.0%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 46000,
    annual_tuition_inr_lakhs: 39.1,
    application_fee_usd: 130,
    deadlines: { fall: "Jan 15 (OUAC / U of T Portal)" },
    required_tests: {
      undergraduate: "Class 12 Boards: 90%+ in Math/Physics/Chem",
      postgraduate: "GRE optional but recommended; 4-year Bachelor degree",
      english_proficiency: "IELTS 6.5+ (no band < 6.0) / TOEFL 100+",
    },
    stem_opt_work_permit: "Up to 3 Years Post-Graduation Work Permit (PGWP) with easy PR pathway",
    popular_majors: ["Computer Engineering", "Applied Science", "Artificial Intelligence", "Commerce (Rotman)"],
    scholarships_available: "Lester B. Pearson International Scholarship (Full 4-year tuition + residence)",
    website: "https://www.utoronto.ca",
  },
  {
    id: "waterloo-canada",
    name: "University of Waterloo",
    country: "Canada",
    city: "Waterloo, Ontario",
    qs_world_ranking: 112,
    flag: "🇨🇦",
    acceptance_rate: "21.0%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 48000,
    annual_tuition_inr_lakhs: 40.8,
    application_fee_usd: 125,
    deadlines: { fall: "Feb 1" },
    required_tests: {
      undergraduate: "Euclid Math Contest recommended; 92%+ in Class 12",
      postgraduate: "GRE Quant 165+; strong coding profile",
      english_proficiency: "IELTS 7.0+ (writing 6.5) / TOEFL 90+",
    },
    stem_opt_work_permit: "3 Years PGWP + World-famous paid Co-Op program (earn while studying)",
    popular_majors: ["Software Engineering (Co-Op)", "Computer Science", "Mechatronics Engineering", "Actuarial Science"],
    scholarships_available: "President's International Experience Award & Faculty Entrance Scholarships",
    website: "https://uwaterloo.ca",
  },

  // Germany
  {
    id: "tum-germany",
    name: "Technical University of Munich (TUM)",
    country: "Germany",
    city: "Munich, Bavaria",
    qs_world_ranking: 37,
    flag: "🇩🇪",
    acceptance_rate: "8.0%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 6000,
    annual_tuition_inr_lakhs: 5.1,
    application_fee_usd: 50,
    deadlines: { fall: "May 31 (Uni-Assist / TUMonline)", spring: "Nov 30" },
    required_tests: {
      undergraduate: "APS Certificate mandatory for Indian applicants + German/English B2/C1",
      postgraduate: "GATE score or GRE accepted; aptitude test / assessment interview",
      english_proficiency: "IELTS 6.5+ / TOEFL 88+",
    },
    stem_opt_work_permit: "18-Month Job Seeker Visa after graduation in Germany / EU Blue Card",
    popular_majors: ["Informatics (Computer Science)", "Automotive Engineering", "Data Engineering", "Robotics"],
    scholarships_available: "DAAD Scholarships, Deutschlandstipendium (€300/month)",
    website: "https://www.tum.de",
  },
  {
    id: "rwth-aachen-germany",
    name: "RWTH Aachen University",
    country: "Germany",
    city: "Aachen, North Rhine-Westphalia",
    qs_world_ranking: 106,
    flag: "🇩🇪",
    acceptance_rate: "10.0%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 700,
    annual_tuition_inr_lakhs: 0.6,
    application_fee_usd: 50,
    deadlines: { fall: "March 1 (International Master's)" },
    required_tests: {
      undergraduate: "APS Certificate + Studienkolleg (if applicable)",
      postgraduate: "GRE mandatory for several international Master's (Quant 160+)",
      english_proficiency: "IELTS 6.5+ / TOEFL 90+",
    },
    stem_opt_work_permit: "18-Month Job Seeker Visa with no tuition fee (semester contribution only)",
    popular_majors: ["Mechanical Engineering", "Production Systems", "Electrical Engineering & IT", "Automotive"],
    scholarships_available: "DAAD Master's Stipends, RWTH Education Fund",
    website: "https://www.rwth-aachen.de",
  },

  // Australia
  {
    id: "unimelb-australia",
    name: "University of Melbourne",
    country: "Australia",
    city: "Melbourne, Victoria",
    qs_world_ranking: 14,
    flag: "🇦🇺",
    acceptance_rate: "30.0%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 35000,
    annual_tuition_inr_lakhs: 29.8,
    application_fee_usd: 100,
    deadlines: { fall: "Nov 30 (Semester 1 - Feb intake)", spring: "May 31 (Semester 2 - July intake)" },
    required_tests: {
      undergraduate: "Class 12 Boards: 88-94% depending on course",
      postgraduate: "Bachelor degree with 70%+ from recognized Indian univ",
      english_proficiency: "IELTS 6.5 (no band < 6.0) / PTE Academic 58+",
    },
    stem_opt_work_permit: "2 to 4 Years Post-Study Work Visa (Temporary Graduate Subclass 485)",
    popular_majors: ["Master of Information Technology", "Software Systems", "Biomedical Engineering", "Finance"],
    scholarships_available: "Melbourne International Undergraduate Scholarship (up to 100% fee remission)",
    website: "https://www.unimelb.edu.au",
  },
  {
    id: "unsw-australia",
    name: "UNSW Sydney (University of New South Wales)",
    country: "Australia",
    city: "Sydney, New South Wales",
    qs_world_ranking: 19,
    flag: "🇦🇺",
    acceptance_rate: "33.0%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 34000,
    annual_tuition_inr_lakhs: 28.9,
    application_fee_usd: 100,
    deadlines: { fall: "Nov 30 (Term 1)", spring: "May 31 (Term 2)" },
    required_tests: {
      undergraduate: "Class 12: 85%+ in Maths",
      postgraduate: "Engineering degree with 65-70%+",
      english_proficiency: "IELTS 6.5+ / TOEFL 90+ / PTE 64+",
    },
    stem_opt_work_permit: "2 to 4 Years Post-Study Work Visa in Sydney",
    popular_majors: ["Renewable Energy Engineering", "Quantum Computing", "Computer Engineering", "Civil Eng"],
    scholarships_available: "International Scientia Coursework Scholarship (AUD 20,000/yr)",
    website: "https://www.unsw.edu.au",
  },

  // Singapore
  {
    id: "nus-singapore",
    name: "National University of Singapore (NUS)",
    country: "Singapore",
    city: "Singapore",
    qs_world_ranking: 8,
    flag: "🇸🇬",
    acceptance_rate: "5.0%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 23000,
    annual_tuition_inr_lakhs: 19.5,
    application_fee_usd: 20,
    deadlines: { fall: "Feb 21 (International Qualifications)" },
    required_tests: {
      undergraduate: "Class 12 CBSE/State Board: 95%+ or SAT 1500+ / ACT 34+",
      postgraduate: "GRE 320+ (Quant 165+) + strong research / coding portfolio",
      english_proficiency: "IELTS 6.5+ / TOEFL 92+",
    },
    stem_opt_work_permit: "Ministry of Education (MOE) Tuition Grant with 3-year Singapore employment bond",
    popular_majors: ["School of Computing", "Electrical & Computer Eng", "Artificial Intelligence", "Business Analytics"],
    scholarships_available: "NUS Science & Technology Undergraduate Scholarship (Free tuition + S$6,000 allowance)",
    website: "https://www.nus.edu.sg",
  },

  // Ireland
  {
    id: "tcd-ireland",
    name: "Trinity College Dublin",
    country: "Ireland",
    city: "Dublin, Ireland",
    qs_world_ranking: 81,
    flag: "🇮🇪",
    acceptance_rate: "34.0%",
    degree_levels: ["Bachelors", "Masters", "PhD"],
    annual_tuition_usd: 27000,
    annual_tuition_inr_lakhs: 23.0,
    application_fee_usd: 60,
    deadlines: { fall: "June 30" },
    required_tests: {
      undergraduate: "Class 12: 85%+ overall",
      postgraduate: "Bachelor degree with 65%+ in Computer Science/Engineering",
      english_proficiency: "IELTS 6.5+ (no band < 6.0) / Duolingo 120+",
    },
    stem_opt_work_permit: "2 Years Third Level Graduate Scheme (EU Tech HQ: Google, Meta, Apple in Dublin)",
    popular_majors: ["M.Sc. Computer Science (Data Science/Intelligent Systems)", "Electronic & Computer Eng", "Immunology"],
    scholarships_available: "Government of Ireland International Education Scholarship (€10,000 stipend + fee waiver)",
    website: "https://www.tcd.ie",
  },
];
